version: '3'
services:
  front:
    container_name: front
    build:
      context: ./front/
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: always
    command: sh -c "npm run dev"
